#!/bin/bash
# Setup script for endpoints-memory plugin
# Prompts for API credentials and saves to settings.local

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLUGIN_DIR="$(dirname "$SCRIPT_DIR")"
SETTINGS_FILE="$PLUGIN_DIR/settings.local"

echo "Endpoints Memory Plugin Setup"
echo "=============================="
echo ""

# Check if settings already exist
if [[ -f "$SETTINGS_FILE" ]]; then
  echo "Settings file already exists at: $SETTINGS_FILE"
  read -p "Overwrite? (y/N): " overwrite
  if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
    echo "Setup cancelled."
    exit 0
  fi
fi

# Prompt for credentials
echo ""
echo "Enter your Endpoints API credentials:"
echo ""

read -p "ENDPOINTS_API_URL (e.g., https://endpoints.work): " api_url
if [[ -z "$api_url" ]]; then
  echo "Error: URL is required"
  exit 1
fi

read -p "ENDPOINTS_API_KEY (starts with ep_): " api_key
if [[ -z "$api_key" ]]; then
  echo "Error: API key is required"
  exit 1
fi

# Validate API key format
if [[ ! "$api_key" =~ ^ep_ ]]; then
  echo "Warning: API key doesn't start with 'ep_'"
  read -p "Continue anyway? (y/N): " cont
  if [[ ! "$cont" =~ ^[Yy]$ ]]; then
    exit 1
  fi
fi

# Write settings file
cat > "$SETTINGS_FILE" << EOF
# Endpoints Memory Plugin Settings
# Generated by setup.sh - DO NOT COMMIT

ENDPOINTS_API_URL="$api_url"
ENDPOINTS_API_KEY="$api_key"
EOF

chmod 600 "$SETTINGS_FILE"

echo ""
echo "Settings saved to: $SETTINGS_FILE"
echo ""

# Test the connection
echo "Testing connection..."
if curl -s -f -H "Authorization: Bearer $api_key" "$api_url/api/endpoints" > /dev/null 2>&1; then
  echo "Connection successful!"
else
  echo "Warning: Could not verify connection. Check your credentials."
fi

echo ""
echo "Setup complete! Restart Claude Code to activate hooks."
